# -*- coding: utf-8 -*-
"""First Lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wB0eVQC8RZqq6jfLixxlRSmLeczTr70
"""

"""
Author: Devin Palmer
KUID: 2981964
Date: 9/9/2024
Lab: lab 1650
Last modified: Date file was most recently modified
Purpose: First lab"""


print("My name is Devin Palmer\t")
print("I am a cybersecurity Engineering major\t")
print("My Hobbies include\t")
print("\tLifting\n\tvideo games\n\tsoccer\n")
print("GoodBye!")